package com.aegis.domain;

import com.fasterxml.jackson.annotation.JsonProperty;
import org.springframework.data.annotation.Id;
import org.springframework.data.elasticsearch.annotations.Document;
import org.springframework.data.elasticsearch.annotations.Field;
import org.springframework.data.elasticsearch.annotations.FieldType;

import java.time.Instant;

/**
 * Represents a security alert generated by the correlation engine.
 * Alerts are created when detection rules identify potential security threats.
 */
@Document(indexName = "aegis-alerts")
public class Alert {
    
    @Id
    @JsonProperty("id")
    private String id;
    
    @Field(type = FieldType.Date)
    @JsonProperty("time")
    private Instant time;
    
    @Field(type = FieldType.Keyword)
    @JsonProperty("tenant_id")
    private String tenantId;
    
    @Field(type = FieldType.Byte)
    @JsonProperty("severity")
    private int severity;
    
    @Field(type = FieldType.Text)
    @JsonProperty("title")
    private String title;
    
    @Field(type = FieldType.Text)
    @JsonProperty("description")
    private String description;
    
    @Field(type = FieldType.Keyword)
    @JsonProperty("rule_id")
    private String ruleId;
    
    @Field(type = FieldType.Date)
    @JsonProperty("acknowledged_at")
    private Instant acknowledgedAt;
    
    @Field(type = FieldType.Keyword)
    @JsonProperty("acknowledged_by")
    private String acknowledgedBy;
    
    /**
     * Default constructor
     */
    public Alert() {
    }
    
    /**
     * Constructor with basic fields
     */
    public Alert(String id, Instant time, String tenantId, int severity) {
        this.id = id;
        this.time = time;
        this.tenantId = tenantId;
        this.severity = severity;
    }
    
    // Getters and Setters
    
    public String getId() {
        return id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    
    public Instant getTime() {
        return time;
    }
    
    public void setTime(Instant time) {
        this.time = time;
    }
    
    public String getTenantId() {
        return tenantId;
    }
    
    public void setTenantId(String tenantId) {
        this.tenantId = tenantId;
    }
    
    public int getSeverity() {
        return severity;
    }
    
    public void setSeverity(int severity) {
        this.severity = severity;
    }
    
    public String getTitle() {
        return title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    
    public String getDescription() {
        return description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    
    public String getRuleId() {
        return ruleId;
    }
    
    public void setRuleId(String ruleId) {
        this.ruleId = ruleId;
    }
    
    public Instant getAcknowledgedAt() {
        return acknowledgedAt;
    }
    
    public void setAcknowledgedAt(Instant acknowledgedAt) {
        this.acknowledgedAt = acknowledgedAt;
    }
    
    public String getAcknowledgedBy() {
        return acknowledgedBy;
    }
    
    public void setAcknowledgedBy(String acknowledgedBy) {
        this.acknowledgedBy = acknowledgedBy;
    }
}
