package com.aegis.domain;

import com.fasterxml.jackson.annotation.JsonProperty;
import org.springframework.data.annotation.Id;
import org.springframework.data.elasticsearch.annotations.Document;
import org.springframework.data.elasticsearch.annotations.Field;
import org.springframework.data.elasticsearch.annotations.FieldType;

import java.time.Instant;

/**
 * Represents a security alert generated by the correlation engine.
 * Alerts are created when detection rules identify potential security threats.
 */
@Document(indexName = "aegis-alerts")
public class Alert {
    
    @Id
    @JsonProperty("id")
    private String id;
    
    @Field(type = FieldType.Date)
    @JsonProperty("time")
    private Instant time;
    
    @Field(type = FieldType.Keyword)
    @JsonProperty("tenant_id")
    private String tenantId;
    
    @Field(type = FieldType.Byte)
    @JsonProperty("severity")
    private int severity;
    
    /**
     * Default constructor
     */
    public Alert() {
    }
    
    /**
     * Constructor with basic fields
     */
    public Alert(String id, Instant time, String tenantId, int severity) {
        this.id = id;
        this.time = time;
        this.tenantId = tenantId;
        this.severity = severity;
    }
    
    // Getters and Setters
    
    public String getId() {
        return id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    
    public Instant getTime() {
        return time;
    }
    
    public void setTime(Instant time) {
        this.time = time;
    }
    
    public String getTenantId() {
        return tenantId;
    }
    
    public void setTenantId(String tenantId) {
        this.tenantId = tenantId;
    }
    
    public int getSeverity() {
        return severity;
    }
    
    public void setSeverity(int severity) {
        this.severity = severity;
    }
}
